language: python
python:
    - "3.6"
before_install:
    - sudo add-apt-repository -y ppa:ubuntugis/ppa
    - sudo apt-get update
    - sudo apt-get install -y libgdal-dev gdal-bin
    - gdal-config --version
install:
    - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
    - pip install -r requirements.txt
script:
    - cd src
    - python -m unittest
