language: python
python:
    - "3.6"
before_install:
    - sudo add-apt-repository -y ppa:ubuntugis/ppa
    - sudo apt-get update
    - sudo apt install libspatialindex-dev
    - sudo apt-get install -y libgdal-dev gdal-bin
    - gdal-config --version
install:
    - pip install numpy --upgrade
    - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
    - pip install -r requirements.txt
    - if ! [[ -d src/ui_compiled ]]; then mkdir src/ui_compiled; fi
    - for filename in ui/*.ui; do pyuic5 ${filename} --import-from res_compiled >> src/ui_compiled/${filename:3:-3}.py; done;
script:
    - cd src && python -m unittest
