# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.verticalLayout_4.addWidget(self.openGLWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.lightDockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightDockWidget.sizePolicy().hasHeightForWidth())
        self.lightDockWidget.setSizePolicy(sizePolicy)
        self.lightDockWidget.setMaximumSize(QtCore.QSize(259, 213))
        self.lightDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.lightDockWidget.setObjectName("lightDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ambientSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.ambientSlider.setProperty("value", 20)
        self.ambientSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ambientSlider.setObjectName("ambientSlider")
        self.verticalLayout.addWidget(self.ambientSlider)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.diffuseSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.diffuseSlider.setProperty("value", 80)
        self.diffuseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.diffuseSlider.setObjectName("diffuseSlider")
        self.verticalLayout.addWidget(self.diffuseSlider)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.xLightSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.xLightSpinBox.setMinimum(-100.0)
        self.xLightSpinBox.setSingleStep(0.1)
        self.xLightSpinBox.setProperty("value", 0.5)
        self.xLightSpinBox.setObjectName("xLightSpinBox")
        self.gridLayout.addWidget(self.xLightSpinBox, 1, 0, 1, 1)
        self.yLightSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.yLightSpinBox.setMinimum(-100.0)
        self.yLightSpinBox.setSingleStep(0.1)
        self.yLightSpinBox.setProperty("value", 3.0)
        self.yLightSpinBox.setObjectName("yLightSpinBox")
        self.gridLayout.addWidget(self.yLightSpinBox, 1, 1, 1, 1)
        self.zLightSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.zLightSpinBox.setMinimum(-100.0)
        self.zLightSpinBox.setSingleStep(0.1)
        self.zLightSpinBox.setProperty("value", 0.5)
        self.zLightSpinBox.setObjectName("zLightSpinBox")
        self.gridLayout.addWidget(self.zLightSpinBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.lightDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.lightDockWidget)
        self.projDockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projDockWidget.sizePolicy().hasHeightForWidth())
        self.projDockWidget.setSizePolicy(sizePolicy)
        self.projDockWidget.setMinimumSize(QtCore.QSize(240, 95))
        self.projDockWidget.setMaximumSize(QtCore.QSize(240, 95))
        self.projDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.projDockWidget.setObjectName("projDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orhogonalRadioButton = QtWidgets.QRadioButton(self.dockWidgetContents_2)
        self.orhogonalRadioButton.setChecked(False)
        self.orhogonalRadioButton.setObjectName("orhogonalRadioButton")
        self.verticalLayout_2.addWidget(self.orhogonalRadioButton)
        self.perspectiveRadioButton = QtWidgets.QRadioButton(self.dockWidgetContents_2)
        self.perspectiveRadioButton.setChecked(True)
        self.perspectiveRadioButton.setObjectName("perspectiveRadioButton")
        self.verticalLayout_2.addWidget(self.perspectiveRadioButton)
        self.projDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.projDockWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.displayDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.displayDockWidget.setFloating(False)
        self.displayDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.displayDockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.displayDockWidget.setObjectName("displayDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.dockWidgetContents_4)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 1, 1, 1)
        self.xScaleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.xScaleSpinBox.setMinimum(0.01)
        self.xScaleSpinBox.setMaximum(10.0)
        self.xScaleSpinBox.setSingleStep(0.01)
        self.xScaleSpinBox.setProperty("value", 1.0)
        self.xScaleSpinBox.setObjectName("xScaleSpinBox")
        self.gridLayout_5.addWidget(self.xScaleSpinBox, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.yScaleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.yScaleSpinBox.setMinimum(0.01)
        self.yScaleSpinBox.setMaximum(10.0)
        self.yScaleSpinBox.setSingleStep(0.01)
        self.yScaleSpinBox.setProperty("value", 1.0)
        self.yScaleSpinBox.setObjectName("yScaleSpinBox")
        self.gridLayout_5.addWidget(self.yScaleSpinBox, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 2, 1, 1)
        self.zScaleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.zScaleSpinBox.setMinimum(0.01)
        self.zScaleSpinBox.setMaximum(10.0)
        self.zScaleSpinBox.setSingleStep(0.01)
        self.zScaleSpinBox.setProperty("value", 1.0)
        self.zScaleSpinBox.setObjectName("zScaleSpinBox")
        self.gridLayout_5.addWidget(self.zScaleSpinBox, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.alphaSlider = QtWidgets.QSlider(self.dockWidgetContents_4)
        self.alphaSlider.setProperty("value", 80)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName("alphaSlider")
        self.verticalLayout_3.addWidget(self.alphaSlider)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.displayDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.displayDockWidget)
        self.controlsDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.controlsDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.controlsDockWidget.setObjectName("controlsDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.moveCameraLeft = QtWidgets.QPushButton(self.groupBox_4)
        self.moveCameraLeft.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraLeft.setObjectName("moveCameraLeft")
        self.gridLayout_2.addWidget(self.moveCameraLeft, 1, 0, 1, 1)
        self.moveCameraUp = QtWidgets.QPushButton(self.groupBox_4)
        self.moveCameraUp.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraUp.setObjectName("moveCameraUp")
        self.gridLayout_2.addWidget(self.moveCameraUp, 0, 1, 1, 1)
        self.moveCameraRight = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveCameraRight.sizePolicy().hasHeightForWidth())
        self.moveCameraRight.setSizePolicy(sizePolicy)
        self.moveCameraRight.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraRight.setObjectName("moveCameraRight")
        self.gridLayout_2.addWidget(self.moveCameraRight, 1, 2, 1, 1)
        self.moveCameraForward = QtWidgets.QPushButton(self.groupBox_4)
        self.moveCameraForward.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraForward.setObjectName("moveCameraForward")
        self.gridLayout_2.addWidget(self.moveCameraForward, 0, 0, 1, 1)
        self.moveCameraBackward = QtWidgets.QPushButton(self.groupBox_4)
        self.moveCameraBackward.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraBackward.setObjectName("moveCameraBackward")
        self.gridLayout_2.addWidget(self.moveCameraBackward, 0, 2, 1, 1)
        self.moveCameraDown = QtWidgets.QPushButton(self.groupBox_4)
        self.moveCameraDown.setMinimumSize(QtCore.QSize(1, 0))
        self.moveCameraDown.setObjectName("moveCameraDown")
        self.gridLayout_2.addWidget(self.moveCameraDown, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.controlsDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.controlsDockWidget)
        self.actionHideInvisible = QtWidgets.QAction(MainWindow)
        self.actionHideInvisible.setCheckable(True)
        self.actionHideInvisible.setObjectName("actionHideInvisible")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenAnother = QtWidgets.QAction(MainWindow)
        self.actionOpenAnother.setObjectName("actionOpenAnother")
        self.actionGrabKeyboard = QtWidgets.QAction(MainWindow)
        self.actionGrabKeyboard.setCheckable(True)
        self.actionGrabKeyboard.setObjectName("actionGrabKeyboard")
        self.actionGrabMouse = QtWidgets.QAction(MainWindow)
        self.actionGrabMouse.setCheckable(True)
        self.actionGrabMouse.setObjectName("actionGrabMouse")
        self.menu.addAction(self.actionOpenAnother)
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionGrabKeyboard)
        self.toolBar.addAction(self.actionGrabMouse)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.lightDockWidget.setWindowTitle(_translate("MainWindow", "Light Source"))
        self.label.setText(_translate("MainWindow", "Ambient strenght"))
        self.label_2.setText(_translate("MainWindow", "Light source strength"))
        self.groupBox.setTitle(_translate("MainWindow", "Position"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.projDockWidget.setWindowTitle(_translate("MainWindow", "Projection"))
        self.orhogonalRadioButton.setText(_translate("MainWindow", "Orthogonal"))
        self.perspectiveRadioButton.setText(_translate("MainWindow", "Perspective"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.displayDockWidget.setWindowTitle(_translate("MainWindow", "Display"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Scaling"))
        self.label_17.setText(_translate("MainWindow", "Y"))
        self.label_18.setText(_translate("MainWindow", "X"))
        self.label_19.setText(_translate("MainWindow", "Z"))
        self.label_6.setText(_translate("MainWindow", "Transparency"))
        self.controlsDockWidget.setWindowTitle(_translate("MainWindow", "Camera"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Controls"))
        self.moveCameraLeft.setText(_translate("MainWindow", "◀"))
        self.moveCameraUp.setText(_translate("MainWindow", "▲"))
        self.moveCameraRight.setText(_translate("MainWindow", "▶"))
        self.moveCameraForward.setText(_translate("MainWindow", "×"))
        self.moveCameraBackward.setText(_translate("MainWindow", "•"))
        self.moveCameraDown.setText(_translate("MainWindow", "▼"))
        self.actionHideInvisible.setText(_translate("MainWindow", "Hide Invisible Edges"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpenAnother.setText(_translate("MainWindow", "Open Another"))
        self.actionGrabKeyboard.setText(_translate("MainWindow", "Grab Keyboard"))
        self.actionGrabMouse.setText(_translate("MainWindow", "Grab Mouse"))


