# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/open_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenDialog(object):
    def setupUi(self, OpenDialog):
        OpenDialog.setObjectName("OpenDialog")
        OpenDialog.resize(924, 479)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(OpenDialog)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fileNameEdit = QtWidgets.QLineEdit(OpenDialog)
        self.fileNameEdit.setReadOnly(True)
        self.fileNameEdit.setObjectName("fileNameEdit")
        self.horizontalLayout_3.addWidget(self.fileNameEdit)
        self.openButton = QtWidgets.QPushButton(OpenDialog)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_3.addWidget(self.openButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(OpenDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.minLat = QtWidgets.QLabel(self.groupBox)
        self.minLat.setObjectName("minLat")
        self.horizontalLayout.addWidget(self.minLat)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.maxLat = QtWidgets.QLabel(self.groupBox)
        self.maxLat.setObjectName("maxLat")
        self.horizontalLayout.addWidget(self.maxLat)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.minLon = QtWidgets.QLabel(self.groupBox)
        self.minLon.setObjectName("minLon")
        self.horizontalLayout_2.addWidget(self.minLon)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.maxLon = QtWidgets.QLabel(self.groupBox)
        self.maxLon.setObjectName("maxLon")
        self.horizontalLayout_2.addWidget(self.maxLon)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(OpenDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.latSlider = QtWidgets.QSlider(self.groupBox_2)
        self.latSlider.setEnabled(False)
        self.latSlider.setOrientation(QtCore.Qt.Horizontal)
        self.latSlider.setObjectName("latSlider")
        self.horizontalLayout_6.addWidget(self.latSlider)
        self.latSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.latSpin.setEnabled(False)
        self.latSpin.setSingleStep(0.05)
        self.latSpin.setObjectName("latSpin")
        self.horizontalLayout_6.addWidget(self.latSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lonSlider = QtWidgets.QSlider(self.groupBox_2)
        self.lonSlider.setEnabled(False)
        self.lonSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lonSlider.setObjectName("lonSlider")
        self.horizontalLayout_5.addWidget(self.lonSlider)
        self.lonSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.lonSpin.setEnabled(False)
        self.lonSpin.setSingleStep(0.05)
        self.lonSpin.setObjectName("lonSpin")
        self.horizontalLayout_5.addWidget(self.lonSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.radSlider = QtWidgets.QSlider(self.groupBox_2)
        self.radSlider.setEnabled(False)
        self.radSlider.setOrientation(QtCore.Qt.Horizontal)
        self.radSlider.setObjectName("radSlider")
        self.horizontalLayout_4.addWidget(self.radSlider)
        self.radSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.radSpin.setEnabled(False)
        self.radSpin.setSingleStep(0.05)
        self.radSpin.setObjectName("radSpin")
        self.horizontalLayout_4.addWidget(self.radSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.pointNumber = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pointNumber.setFont(font)
        self.pointNumber.setObjectName("pointNumber")
        self.horizontalLayout_7.addWidget(self.pointNumber)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.autoUpdateCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.autoUpdateCheckBox.setObjectName("autoUpdateCheckBox")
        self.verticalLayout.addWidget(self.autoUpdateCheckBox)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.closeButton = QtWidgets.QPushButton(OpenDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_8.addWidget(self.closeButton)
        self.saveButton = QtWidgets.QPushButton(OpenDialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_8.addWidget(self.saveButton)
        self.previewButton = QtWidgets.QPushButton(OpenDialog)
        self.previewButton.setEnabled(False)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout_8.addWidget(self.previewButton)
        self.okButton = QtWidgets.QPushButton(OpenDialog)
        self.okButton.setEnabled(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_8.addWidget(self.okButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.previewGroupBox = QtWidgets.QGroupBox(OpenDialog)
        self.previewGroupBox.setObjectName("previewGroupBox")
        self.previewLayout = QtWidgets.QVBoxLayout(self.previewGroupBox)
        self.previewLayout.setObjectName("previewLayout")
        self.previewLabel = QtWidgets.QLabel(self.previewGroupBox)
        self.previewLabel.setObjectName("previewLabel")
        self.previewLayout.addWidget(self.previewLabel)
        self.horizontalLayout_9.addWidget(self.previewGroupBox)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 3)

        self.retranslateUi(OpenDialog)
        self.closeButton.clicked.connect(OpenDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OpenDialog)

    def retranslateUi(self, OpenDialog):
        _translate = QtCore.QCoreApplication.translate
        OpenDialog.setWindowTitle(_translate("OpenDialog", "Dialog"))
        self.fileNameEdit.setPlaceholderText(_translate("OpenDialog", "File is not open"))
        self.openButton.setText(_translate("OpenDialog", "Open"))
        self.groupBox.setTitle(_translate("OpenDialog", "File parameters"))
        self.label.setText(_translate("OpenDialog", "Latitude:"))
        self.minLat.setText(_translate("OpenDialog", "0"))
        self.label_2.setText(_translate("OpenDialog", "-"))
        self.maxLat.setText(_translate("OpenDialog", "0"))
        self.label_3.setText(_translate("OpenDialog", "Longitude:"))
        self.minLon.setText(_translate("OpenDialog", "0"))
        self.label_4.setText(_translate("OpenDialog", "-"))
        self.maxLon.setText(_translate("OpenDialog", "0"))
        self.groupBox_2.setTitle(_translate("OpenDialog", "Area selection parameters"))
        self.label_5.setText(_translate("OpenDialog", "Latitude"))
        self.label_6.setText(_translate("OpenDialog", "Longitude"))
        self.label_7.setText(_translate("OpenDialog", "Radius"))
        self.label_8.setText(_translate("OpenDialog", "Number of points"))
        self.pointNumber.setText(_translate("OpenDialog", "0"))
        self.autoUpdateCheckBox.setText(_translate("OpenDialog", "Preview autoupdate"))
        self.closeButton.setText(_translate("OpenDialog", "Exit"))
        self.saveButton.setText(_translate("OpenDialog", "Save area"))
        self.previewButton.setText(_translate("OpenDialog", "Preview"))
        self.okButton.setText(_translate("OpenDialog", "OK"))
        self.previewGroupBox.setTitle(_translate("OpenDialog", "Area preview"))
        self.previewLabel.setText(_translate("OpenDialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Course work for discipline<br/>&quot;Computer graphics&quot;</span></p><p align=\"center\">Authors: <span style=\" font-style:italic;\">Korytov Pavel, Piskunov Yaroslav<br/>Saint-Petersburg State Electrotechnical University<br/>Group: 6304</span></p><p align=\"center\">This program draws a 3d topographic map of a GeoTIFF file</p><p align=\"center\">Open a file to start. Press &quot;preview&quot; to toggle preview of<br/>the selected area</p><p align=\"center\"><span style=\" font-weight:600;\">Warning</span>: the number of points greater than TODO can<br/>cause a shortage of RAM</p></body></html>"))


